## Chapter7.4 多クラスの対応

In [1]:
import numpy as np

one-hot-vector

1つだけ変換する場合

In [2]:
onehot = [0, 0, 1, 0]  # 4クラス、ラベル2
label = np.argmax(onehot)
label

2

複数変換する場合

In [3]:
onehot = [[1, 0, 0, 0],
          [0, 0, 1, 0]]
labels = np.argmax(onehot, axis=1)
labels

array([0, 2])

数値ラベルからone-hot-vectorへ

In [4]:
label = 2
onehot = np.zeros(4)  # [0, 0, 0, 0]
onehot[label] = 1     # [0, 0, 1, 0]
onehot

array([ 0.,  0.,  1.,  0.])

In [5]:
from sklearn.preprocessing import OneHotEncoder

# クラス数4でエンコーダーを作成
enc = OneHotEncoder(n_values=4)

labels = [[0],
          [2]]

# 数値クラスからone-hot-vectorへ変換
enc.fit_transform(labels).toarray()

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.]])

ソフトマックス関数

In [6]:
def softmax(scores):
    f = scores
    f -= np.max(f)
    return np.exp(f) / np.sum(np.exp(f))

outputs = np.array([1, 2, 788, 789])  # 出力層の出力（4ユニット）
pred = softmax(outputs)

# print時のフォーマットを揃える
np.set_printoptions(formatter={'float': '{: 0.6f}'.format})
pred

array([ 0.000000,  0.000000,  0.268941,  0.731059])

損失関数

In [7]:
# 平均二乗誤差
def mse(pred, label):
    return 0.5 * np.sum((pred - label)**2)


pred = np.array([0.000000, 0.000000, 0.268941, 0.731059])  # 推論
label = np.array([0, 0, 0, 1])  # 正解ラベル

mse(pred, label)

0.072329261480999996

In [8]:
def cross_entropy(pred, label):
    # np.log(0)は-infとなるので、clipで0にならないよう調整
    return -np.sum(label * np.log(pred.clip(1e-6)))


pred = np.array([0.000000, 0.000000, 0.268941, 0.731059])  # 推論
label = np.array([0, 0, 0, 1])  # 正解ラベル

cross_entropy(pred, label)

0.31326111113503546