## Chapter2.2 Numpyとpandas

In [1]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)

In [2]:
a.shape

(2, 3)

In [3]:
a.reshape((3, 2))

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

In [4]:
a.dtype

dtype('int32')

In [5]:
b = np.array([[[1, 2, 3],
               [4, 5, 6]],
              [[7, 8, 9],
               [0, 1, 2]]], dtype=np.int32)
b.shape

(2, 2, 3)

In [6]:
a[0, 1]

2

**ndarrayの生成方法**

In [7]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(2, 3, 0.1)

array([ 2. ,  2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9])

**ユニバーサル関数**

In [10]:
np.power(a, 2)

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [11]:
def func(x):
    return 'Label:{}'.format(x)


np_func = np.frompyfunc(func, 1, 1)
np_func(a)

array([['Label:1', 'Label:2', 'Label:3'],
       ['Label:4', 'Label:5', 'Label:6']], dtype=object)

In [12]:
func(a)

'Label:[[1 2 3]\n [4 5 6]]'

**ブロードキャスティング**

In [13]:
a + 10

array([[11, 12, 13],
       [14, 15, 16]], dtype=int32)

In [14]:
a + a

array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)

In [15]:
c = np.array([[1],
              [2]], dtype=np.int32)
# 次のように拡張される
# array([[1, 1, 1],
#        [2, 2, 2]])

a + c

array([[2, 3, 4],
       [6, 7, 8]], dtype=int32)

In [16]:
d = np.array([[1, 2, 3]], dtype=np.int32)
# 次のように拡張される
# array([[1, 2, 3],
#        [1, 2, 3]])

a + d

array([[2, 4, 6],
       [5, 7, 9]], dtype=int32)

In [17]:
e = np.array([[1, 2],
              [1, 2]], dtype=np.int32)
# これは拡張できない

# a + e  # <- 実行するとエラー

**pandas**

In [18]:
import pandas as pd

series_a = pd.Series([1.1, 2.2, 3.3])
series_a

0    1.1
1    2.2
2    3.3
dtype: float64

In [19]:
series_b = pd.Series([10, 20, 30], index=['Apple', 'Orange', 'Grape'])
series_b

Apple     10
Orange    20
Grape     30
dtype: int64

In [20]:
series_c = pd.Series({'Apple': 120, 'Orange': 80, 'Grape': 300})
series_c

Apple     120
Grape     300
Orange     80
dtype: int64

In [21]:
series_c['Orange']

80

In [22]:
series_d = pd.Series([2, 4, 6, 8, 10, 12])
series_d[1:3]

1    4
2    6
dtype: int64

In [23]:
df_a = pd.DataFrame([[1, 2, 3],
                     [4, 5, 6]],
                    columns=['a', 'b', 'c'],
                    index=['A', 'B'])
df_a

a  b  c
A  1  2  3
B  4  5  6

In [24]:
df_a.a

A    1
B    4
Name: a, dtype: int64

In [25]:
df_a.mean()

a    2.5
b    3.5
c    4.5
dtype: float64

In [26]:
df_a.mean(axis=1)

A    2.0
B    5.0
dtype: float64

In [27]:
def func(x):
    mn = x.min()
    mx = x.max()
    return mx - mn

df_a.apply(func, axis=0)

a    3
b    3
c    3
dtype: int64